[theme]
# Primary accent color
primaryColor = "#d33682"

# Background color
backgroundColor = "#002b36"

# Background color for the sidebar and most interactive elements
secondaryBackgroundColor = "#586e75"

# Color used for almost all text
textColor = "#fff"